name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})

    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: go
          build-mode: autobuild
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.x' ]
        
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    # - name: Initializing CodeQL
    #   uses: github/codeql-action/init@v3
    #   with:
    #     language: go
    #     config-file: .github/workflows/codeql/codeql-config.yml

    - name: Install Dependencies
      run: go get -t -u ./...

    - name: Build
      run: go build -v ./...

    # - name: Test
    #   run: go test -v

    # - name: Upload Test Results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: Go-results-${{ matrix.go-version }}
    #     path: TestResults-${{ matrix.go-version }}.json

    # - name: Perform CodeQL Analysis
    #   uses: github/codeql-action/analyze@v3
     
