name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup go
        uses: actions/setup-go@latest
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@lates

      - name: Test
        run: go test ./...
